sudo: required

language: python
python:
  - '3.7'

addons:
  chrome: stable

services:
  - docker

# We need to run our own couchdb because Travis doesn't use credentials
before_install:
  - docker pull couchdb:latest
  - docker run -d --name couchdb -p 5984:5984 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=pass
    couchdb:latest
  - docker ps -a

env:
  - BINDING_CLOUDANT='{"username":"admin","password":"pass","host":"localhost","port":5984,"url":"http://admin:pass@localhost:5984"}'

# command to install dependencies
install: 
  - sudo apt-get install -y chromium-chromedriver python3-selenium
  - pip install -r requirements.txt

before_script:
  - chromedriver --version
  - curl -X GET http://localhost:5984/
  - curl -X PUT http://admin:pass@localhost:5984/test
  - gunicorn --log-level=critical --bind=127.0.0.1:5000 service:app &  # start a Web server in the background
  - sleep 5 # give Web server some time to bind to sockets, etc
  - curl -I http://localhost:5000/  # make sure the service is up

script:
  - nosetests
  - behave
  # - nosetests tests/test_selenium.py
  # - coverage run tests/test_server.py

after_success:
  - codecov
