apiVersion: k3d.io/v1alpha3
kind: Simple
name: nyu-devops
servers: 1
agents: 1
ports:
- port: 8080:80
  nodeFilters:
  - loadbalancer
registries:
  create: 
    name: cluster-registry
    host: "0.0.0.0"
    hostPort: "5000"
  config: |
    mirrors:
      "cluster-registry":
        endpoint:
          - http://cluster-registry:5000
